In [3]:
%cd "../biovector/biovector"

C:\Users\mceau\Documents\biovector\biovector

In [39]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'tabulate'

In [5]:
import bv_utils
import interactive, stats, __main__, workout

In [113]:
weights = pd.read_csv('../data/measures/weight.csv')
sets = pd.read_csv('../data/sets.csv')
exercises = pd.read_csv('../data/exercises.csv')

In [114]:
sets.tail()

,Timestamp,Time,Number,Workout Name,Program,ID,Exercise Name,Weight,Reps,User Weight,Pred1RL,1RL,Pred1RM,1RM,Int,h,Load,phi,Notes
10760,1.649746e+09,2022-04-12 08:38:55,1378.0,bp,monolith,P01.00,Bench Press,49.0,10.0,98.0,33.00,68.0,65.0,135.0,0.490000,0.000000,245.0,0.000000,NaN
10761,1.649746e+09,2022-04-12 08:38:55,1378.0,bp,monolith,P01.00,Bench Press,49.0,10.0,98.0,33.00,68.0,65.0,135.0,0.490000,0.000000,245.0,0.000000,NaN
10762,1.649746e+09,2022-04-12 08:38:55,1378.0,bp,monolith,P01.00,Bench Press,49.0,8.0,98.0,31.00,68.0,62.0,135.0,0.460000,0.000000,196.0,0.000000,NaN
10763,1.649830e+09,2022-04-13 08:06:36,1379.0,kb,monolith,H20.0,Kettlebell Swing,32.0,50.0,98.0,164.00,267.0,85.0,139.0,0.610000,0.000000,3080.0,0.000000,NaN
10764,1.649856e+09,2022-04-13 15:24:51,1380.0,sq,à changer,S00,Squat,125.0,6.0,98.0,173.94,183.0,150.0,162.0,0.950492,1.049655,869.7,912.884727,NaN

In [107]:
sets.columns

Index(['Timestamp', 'Time', 'Number', 'Workout Name', 'Program', 'ID',
       'Exercise Name', 'Weight', 'Reps', 'User Weight', 'Pred1RL', '1RL',
       'Pred1RM', '1RM', 'Int', 'h', 'Load', 'phi', 'Notes'],
      dtype='object')

In [108]:
workout = sets[sets['Number'] == 1000]
wex = set(workout['ID'].values)
wexd = {i : {k:v for k,v in zip(exercises.columns,exercises[exercises['ID']==i].to_numpy()[0])} for i in wex}

In [112]:
workout[["Time","Weight","Reps","Pred1RL","1RL","Pred1RM","1RM","Int","h"]]

,Timestamp,Time,Number,Workout Name,Program,ID,Exercise Name,Weight,Reps,User Weight,Pred1RL,1RL,Pred1RM,1RM,Int,h,Load,phi,Notes
2289,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,48.0,10.0,87.4,80.0,146.0,64.0,188.0,0.55,0.00,603.0,0.0,NaN
2290,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,68.0,5.0,87.4,84.0,146.0,79.0,188.0,0.58,0.00,361.0,0.0,NaN
2291,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,88.0,5.0,87.4,98.0,146.0,103.0,188.0,0.67,0.04,421.0,17.0,NaN
2292,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,106.0,5.0,87.4,111.0,146.0,124.0,188.0,0.76,0.63,475.0,299.0,NaN
2293,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,124.0,5.0,87.4,123.0,146.0,145.0,188.0,0.84,1.02,529.0,540.0,NaN
2294,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,H00.0,Deadlift,140.0,6.0,87.4,139.0,146.0,168.0,188.0,0.95,1.05,693.0,728.0,NaN
2295,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2296,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2297,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2298,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2299,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2300,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,P21,Ring Dips,0.0,8.0,87.4,44.0,46.0,0.0,0.0,0.96,1.05,280.0,294.0,NaN
2301,1.532612e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,S11,Zercher Squat (Barbell),81.0,5.0,87.4,137.0,143.0,94.0,105.0,0.96,1.05,589.0,618.0,NaN
2302,1.532613e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,S11,Zercher Squat (Barbell),85.0,5.0,87.4,141.0,143.0,99.0,105.0,0.99,1.05,603.0,633.0,NaN
2303,1.532613e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,S11,Zercher Squat (Barbell),95.0,5.0,87.4,149.0,143.0,111.0,105.0,1.04,1.05,638.0,670.0,NaN
2304,1.532613e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,S11,Zercher Squat (Barbell),95.0,5.0,87.4,149.0,149.0,111.0,111.0,1.00,1.05,638.0,670.0,NaN
2305,1.532613e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,S11,Zercher Squat (Barbell),95.0,5.0,87.4,149.0,149.0,111.0,111.0,1.00,1.05,638.0,670.0,NaN
2306,1.532613e+09,2018-07-26 15:29:11,1000.0,DL - 5/3/1 #1000,NaN,L11.2,Nordic Hamstring Curl (Assisted),30.0,11.0,87.4,62.0,68.0,41.0,45.0,0.91,1.05,501.0,526.0,NaN